### ISSUE TITLE
Add snippet - blank screen

### ISSUE THREAD

**Issue by ijwelch** [sleeptil3/codelockr-react#9] opened 2021-05-25 23:34 UTC
Add a new snippet (when library is not empty, Objective-C, private) and get landed on a blank page.

The new snippet was saved successfully.

**Comment by sleeptil3** [comment] 2021-05-26 00:15
Yeah I’ve had that issue a couple times though inconsistently and a refresh usually fixes it. It’s meant to redirect you back to the folder that the snippet was added to and it seems it’s beating it to the punch before the snippets update. I’ll try a couple things. Thanks!

**Comment by sleeptil3** [comment] 2021-05-26 01:36
I found the cause of the issue. it needed to refresh the list of folders before sending you back to the snippet view after a new folder was created. i believe it is fixed now.

**Closed by sleeptil3** 2021-05-26 01:36 UTC
